Added security details docs
highcharts/connectors-morningstar pull request #49
Opened 2024-11-19 09:27 UTC by bm64

Added security details docs

2024-11-19 11:10 UTC, pawelfus requested changes
Missing demo in `demos/` directory

2024-11-19 13:40 UTC, kamil-musialowski approved these changes
All good aside from Pawel's comment. Once https://github.com/highcharts/highcharts/pull/22174 is merged, we should add the docs there.

2024-11-19 14:28 UTC, pawelfus approved these changes

2024-11-22 13:19 UTC, DJTechnoo approved these changes

2024-11-28 20:19 UTC, TorsteinHonsi approved these changes
Looks good 👍

2024-11-29 10:04 UTC, merged