Feature/investment screener
highcharts/connectors-morningstar pull request #52
Opened 2024-11-21 10:42 UTC by pawellysy

2024-11-26 08:59 UTC, DJTechnoo requested changes
Path not found because of typo

2024-11-26 08:59 UTC, DJTechnoo commented on demos/index.html
> +            <li><a href="dashboards-investment-screener//demo.html">Highcharts Dashboards + Morningstar Investment Screener</a></li>
One too many '/'

2024-11-26 13:06 UTC, pawelfus requested changes
Nice! Just a minor polishing: 

- Docs are missing (see `docs/connectors/*.md` for inspiration). It seems you created `src/Screeners/../README.md` file but is missing most of the content.
- Add some comments to the demo.js file. Start with desc for functions and filters

2024-11-27 08:30 UTC, bre1470 approved these changes

2024-11-27 09:34 UTC, DJTechnoo approved these changes

2024-11-28 15:01 UTC, pawelfus requested changes
- conflicts
- typo `this` -> `This`

2024-11-28 15:32 UTC, kamil-musialowski commented on demos/dashboards-investment-screener/demo.js
> +            // fail silently
Do we leave that here or add some i.e console.log/warn?

2024-11-28 15:33 UTC, kamil-musialowski commented on docs/connectors/morningstar/screeners/investment-screener.md
> +Investment Screener connector
Since these are used as Docs titles on Docs sidebar, I would remove the connector bit
```suggestion
Investment Screener
```

2024-11-28 15:33 UTC, kamil-musialowski commented on docs/connectors/morningstar/screeners/investment-screener.md
> +Using Morningstar Investment Screener endpoint you are able filter Morningstar's database of global investments using hundreds of data points including Morningstar prorietary data.
```suggestion
Using Morningstar Investment Screener endpoint allows you to filter Morningstar's database of global investments using hundreds of data points including Morningstar proprietary data.
```

2024-11-28 15:34 UTC, kamil-musialowski commented on docs/connectors/morningstar/screeners/investment-screener.md
> +this connector is designed to be interacted with using some external buttons, that might filter data on the backend, provide pagiantion as well as sorting.
```suggestion
this connector is designed to be interacted with using external buttons, that might filter data on the backend, provide pagination as well as sorting.
```

2024-11-28 15:36 UTC, kamil-musialowski commented on docs/connectors/morningstar/screeners/investment-screener.md
> +    langageId: 'en-GB',
```suggestion
    languageId: 'en-GB',
```

2024-11-28 20:23 UTC, TorsteinHonsi approved these changes
Thanks, looks good to me!

2024-11-29 12:08 UTC, kamil-musialowski approved these changes

2024-11-29 13:01 UTC, pawelfus approved these changes
Thanks!

2024-11-29 13:01 UTC, merged