fetch-demo
highcharts/connectors-morningstar pull request #53
Opened 2024-11-22 13:17 UTC by DJTechnoo

Added a demo showing how to manually fetch data without the connector.

2024-11-26 07:00 UTC, pawellysy approved these changes
minor polishing apart from that looks good!

2024-11-26 07:00 UTC, pawellysy commented on demos/manual-fetch/demo.js
> +        // Fail silently
add the console log here, or there is no point in writing error msgs where you throw them.

2024-11-26 13:27 UTC, pawelfus requested changes
Looks good, just a tiny request

2024-11-26 13:27 UTC, pawelfus commented on demos/manual-fetch/demo.js
> +            type: 'datetime',
`datetime` is default in Stock, no need to set this explicit

2024-11-26 17:28 UTC, kamil-musialowski approved these changes

2024-11-27 08:29 UTC, bre1470 approved these changes

2024-11-27 09:09 UTC, pawelfus approved these changes

2024-11-27 09:09 UTC, merged