Security Details Portfolios data
highcharts/connectors-morningstar pull request #55
Opened 2024-11-27 10:59 UTC by bm64

wip

2024-11-29 10:52 UTC, pawellysy approved these changes

2024-11-29 12:09 UTC, DJTechnoo approved these changes

2024-12-02 15:28 UTC, kamil-musialowski approved these changes

2024-12-05 11:06 UTC, pawelfus requested changes
Missing:
- docs update (how to use it)
- tests ?
- API changes?
- at least one demo/sample

2024-12-06 12:11 UTC, pawelfus requested changes
+tests are failing

2024-12-06 12:11 UTC, pawelfus commented on demos/stock-securitydetails-asset-allocations/demo.js
> +    const connector = new Connectors.Morningstar.SecurityDetailsConnector({
HighchartsConnectors*

2024-12-06 12:11 UTC, pawelfus commented on demos/stock-securitydetails-asset-allocations/demo.js
> +        type: 'AssetAllocations'
How about setting this option on the `converter` level? What do you think @bre1470 ?

2024-12-06 12:11 UTC, pawelfus commented on demos/stock-securitydetails-asset-allocations/demo.js
> +            if (Connectors.Morningstar.isPostmanEnvironmentJSON(fileJSON)) {
HighchartsConnectors

2024-12-06 12:11 UTC, pawelfus commented on tests/SecurityDetails/SecurityDetailsConnector.test.ts
> +        }
No need to specify `type`? Here in all other tests? Why the tests pass without it?

2024-12-11 12:51 UTC, pawelfus requested changes
Nice! Just a few minor bugs.

It seems the API ref does not describe the `type` correctly:

![image](https://github.com/user-attachments/assets/407b84d9-8b14-44cb-9c84-1d74b83ee1f5)

2024-12-11 12:51 UTC, pawelfus commented on demos/stock-securitydetails-asset-allocations/demo.js
> +        type: 'AssetAllocations'
Wrong API option, demo doesn't work

2024-12-11 12:51 UTC, pawelfus commented on demos/stock-securitydetails-asset-allocations/demo.js
> +            if (HighchartsConnectors.Morningstar.isPostmanEnvironmentJSON(fileJSON)) {
Wrong path. Should be `HighchartsConnectors.Morningstar.Shared.isPostmanEnvironmentJSON`

2025-01-17 06:23 UTC, bre1470 commented on src/SecurityDetails/SecurityDetailsOptions.ts
> +    converter?: SecurityDetailsConverterOptions
This is just an idea: You might consider (in the future) to also support multiple converters simultaneously and move the `table.deleteColumns` to the connector. The abstract `MorningstarConverter` then will need a second constructor argument for a shared connector-table to start with.

2025-01-17 06:23 UTC, bre1470 approved these changes
Looks good! 👍

2025-02-03 07:29 UTC, TorsteinHonsi approved these changes
Thanks!

2025-02-03 09:03 UTC, merged