bugfix/xray-connector-invalid-response
highcharts/connectors-morningstar pull request #56
Opened 2024-11-27 11:33 UTC by kamil-musialowski

Fixed #54, response from xray converter was incorrect.

2024-12-09 19:23 UTC, kamil-musialowski commented
_force push due to incorrect commit name, missing `GlobalStockSector`_

2025-01-08 13:59 UTC, pawelfus requested changes
Nice!

In addition to the inline comments, there is a bug when scrolling down in tables. Is this a bug in DataGrid (please report it then) or in the implementation (please fix it then)? 

<img width="746" alt="image" src="https://github.com/user-attachments/assets/89afda91-dbe9-4988-a6cf-54e024fcc85b" />

2025-01-08 13:59 UTC, pawelfus commented on demos/dashboards-xray/demo.html
> +        <script src="https://code.highcharts.com/highcharts.js"></script>
Do we need core lib here?

2025-01-08 13:59 UTC, pawelfus commented on demos/dashboards-xray/demo.js
> +    99: 'Other' // ??
In progress..

2025-01-08 13:59 UTC, pawelfus commented on demos/dashboards-xray/demo.js
> +    99: 'Fixed Income'
Please update to the newest categories

2025-01-08 13:59 UTC, pawelfus commented on demos/dashboards-xray/demo.js
> +    99: 'Other', // ??
Not classified

2025-01-08 13:59 UTC, pawelfus commented on demos/dashboards-xray/demo.js
> +    .then(() => {});
Q: Is this `then()` necessary?

2025-01-09 08:38 UTC, kamil-musialowski commented on demos/dashboards-xray/demo.js
> +    .then(() => {});
Nope!

2025-01-09 10:48 UTC, pawelfus commented on demos/dashboards-xray/demo.js
> +    99: 'Other' // ??
"Other" - confirmed

2025-01-09 11:31 UTC, pawelfus approved these changes

2025-01-10 13:47 UTC, DJTechnoo approved these changes

2025-01-13 11:30 UTC, jedrzejruta approved these changes
Nicely done! :tada:

2025-01-14 08:21 UTC, bm64 approved these changes

2025-01-15 13:39 UTC, bre1470 commented on src/XRay/XRayJSON.ts
> +
I do not think that this function is necessary, just do the `globalStockSector` part in `isBreakdowns`.

2025-01-17 13:54 UTC, pawelfus approved these changes
Thanks!

2025-01-17 13:58 UTC, bre1470 approved these changes

2025-01-17 13:58 UTC, bre1470 commented on src/XRay/XRayJSON.ts
>              ) || (
That goes too far with optimization. What I meant is that this can be replaced with 
```
!(json as Breakdowns).regionalExposure ||
isRegionalExposure((json as Breakdowns).regionalExposure?.[0])
```

2025-01-23 07:58 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2025-01-23 15:56 UTC, kamil-musialowski commented
Switching to draft, need to add missing returns.

2025-01-27 16:55 UTC, jedrzejruta approved these changes
Looks good, great work! 🎉

2025-01-29 13:14 UTC, pawelfus approved these changes
Thanks!

2025-02-03 07:28 UTC, TorsteinHonsi approved these changes
Thanks!

2025-02-03 09:04 UTC, merged